/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import models.EmployeeSignUp1_db;
import models.EmployeeSignUp2_db;
import models.EmployeeSignUp3_db;
import models.User_email;
import utils.DBconnection;

/**
 *
 * @author astrodist
 */
public class EmployeeSignUp3 extends javax.swing.JFrame {

    static EmployeeSignUp1_db EmployeeSignUp1_db;
    static EmployeeSignUp2_db EmployeeSignUp2_db;
    static User_email User_email;
    
    

    

    /**
     * Creates new form EmployeeSignUp3
     */
    public EmployeeSignUp3() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        EmployeeSignUp3_exp_radiobutton = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        EmployeeSignUp3_workexp_textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EmployeeSignUp3_orgname_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EmployeeSignUp3_jobtitle_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        EmployeeSignUp3_jobloc_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EmployeeSignUp3_error_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 40)); // NOI18N
        jLabel3.setText("  Experience");
        jLabel3.setToolTipText("");

        jButton1.setBackground(java.awt.Color.black);
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setLabel("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.black);
        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Next");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        EmployeeSignUp3_exp_radiobutton.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp3_exp_radiobutton.setText("I have no prior work experience");
        EmployeeSignUp3_exp_radiobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp3_exp_radiobuttonActionPerformed(evt);
            }
        });
        EmployeeSignUp3_exp_radiobutton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EmployeeSignUp3_exp_radiobuttonKeyPressed(evt);
            }
        });

        jPanel2.setBackground(java.awt.Color.white);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Name of Organization:");
        jLabel1.setToolTipText("");

        EmployeeSignUp3_workexp_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp3_workexp_textfield.setToolTipText("");
        EmployeeSignUp3_workexp_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp3_workexp_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp3_workexp_textfieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Work Experience (Years):");
        jLabel2.setToolTipText("");

        EmployeeSignUp3_orgname_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp3_orgname_textfield.setToolTipText("");
        EmployeeSignUp3_orgname_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp3_orgname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp3_orgname_textfieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel4.setText("Job Title:");
        jLabel4.setToolTipText("");

        EmployeeSignUp3_jobtitle_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp3_jobtitle_textfield.setToolTipText("");
        EmployeeSignUp3_jobtitle_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp3_jobtitle_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp3_jobtitle_textfieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel5.setText("Job Location (City):");
        jLabel5.setToolTipText("");

        EmployeeSignUp3_jobloc_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp3_jobloc_textfield.setToolTipText("");
        EmployeeSignUp3_jobloc_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp3_jobloc_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp3_jobloc_textfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(EmployeeSignUp3_jobtitle_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(EmployeeSignUp3_jobloc_textfield)
                    .addComponent(EmployeeSignUp3_orgname_textfield)
                    .addComponent(EmployeeSignUp3_workexp_textfield)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp3_orgname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp3_jobtitle_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp3_jobloc_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp3_workexp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Enter your latest details!");

        EmployeeSignUp3_error_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(EmployeeSignUp3_exp_radiobutton)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmployeeSignUp3_error_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(EmployeeSignUp3_exp_radiobutton)
                .addGap(37, 37, 37)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp3_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EmployeeSignUp2 sp = new EmployeeSignUp2();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EmployeeSignUp3_workexp_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp3_workexp_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp3_workexp_textfieldActionPerformed

    private void EmployeeSignUp3_orgname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp3_orgname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp3_orgname_textfieldActionPerformed

    private void EmployeeSignUp3_jobtitle_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp3_jobtitle_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp3_jobtitle_textfieldActionPerformed

    private void EmployeeSignUp3_jobloc_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp3_jobloc_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp3_jobloc_textfieldActionPerformed

    private void EmployeeSignUp3_exp_radiobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp3_exp_radiobuttonActionPerformed
       // TODO add your handling code here:
       if(EmployeeSignUp3_exp_radiobutton.isSelected()){
        EmployeeSignUp3_orgname_textfield.setEnabled(false);
        EmployeeSignUp3_jobloc_textfield.setEnabled(false);
        EmployeeSignUp3_jobtitle_textfield.setEnabled(false);
        EmployeeSignUp3_workexp_textfield.setEnabled(false);
       }
       else{
        EmployeeSignUp3_orgname_textfield.setEnabled(true);
        EmployeeSignUp3_jobloc_textfield.setEnabled(true);
        EmployeeSignUp3_jobtitle_textfield.setEnabled(true);
        EmployeeSignUp3_workexp_textfield.setEnabled(true);
       }
                   
    }//GEN-LAST:event_EmployeeSignUp3_exp_radiobuttonActionPerformed

    private void EmployeeSignUp3_exp_radiobuttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmployeeSignUp3_exp_radiobuttonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp3_exp_radiobuttonKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String orgname = "", jobloc = "", jobtitle = "", error = "", workexp="";
        int workexp1=0;
        
        if(!(EmployeeSignUp3_exp_radiobutton.isSelected())){
            orgname = EmployeeSignUp3_orgname_textfield.getText();
            jobloc = EmployeeSignUp3_jobloc_textfield.getText();
            jobtitle = EmployeeSignUp3_jobtitle_textfield.getText();
            workexp = (EmployeeSignUp3_workexp_textfield.getText());
            
            boolean numeric2 = true;
            try {
                Double num2 = Double.parseDouble(workexp);
            }catch (NumberFormatException e) {
                numeric2 = false;
            }

            
            if(orgname.isEmpty() || jobloc.isEmpty() || jobtitle.isEmpty() || workexp.isEmpty()){
                error = "Please fill all details";
            }
            else if(!(jobloc.matches("^[a-zA-Z]*$"))){
                    error = "Please enter valid city name";
            }
            else if(numeric2 == false){
                error = "Enter only numeric values for work experience!";
            }                        
        }
        
        if(error.isEmpty()){
                EmployeeSignUp3_db ep2 = new EmployeeSignUp3_db(orgname, jobloc, jobtitle, workexp);   
//                System.out.println(EmployeeSignUp2_db.getDegreename());
//                System.out.println(EmployeeSignUp2_db.getInstitute());
//                System.out.println(EmployeeSignUp2_db.getQualification());
//                System.out.println(EmployeeSignUp2_db.getScore());
//                System.out.println(EmployeeSignUp2_db.getYear());                
//                System.out.println(EmployeeSignUp1_db.getAdd1());
//                System.out.println(EmployeeSignUp1_db.getAdd2());
//                System.out.println(EmployeeSignUp1_db.getCity());                
//                System.out.println(EmployeeSignUp1_db.getDob());
//                System.out.println(EmployeeSignUp1_db.getFname());
//                System.out.println(EmployeeSignUp1_db.getLname());
//                System.out.println(EmployeeSignUp1_db.getGender());
//                System.out.println(EmployeeSignUp1_db.getTel());
//                System.out.println(User_email.getUser_email());
//                System.out.println(User_email.getUser_employee_0_employer_1());
//                System.out.println(User_email.getUser_password());
                
                try{
                    DBconnection connect = new DBconnection();
                    Connection conn = connect.createConnection(); 
                    Statement stmt = conn.createStatement();

                    String sql = "INSERT INTO `common` (email, password, flag)VALUES (?,?,?)";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, User_email.getUser_email());
                    ps.setString(2, User_email.getUser_password());
                    ps.setInt(3, 0);
                    int r = ps.executeUpdate();
                    if (r>0)System.out.println("\nSuccessful User-email entry!");

                    ResultSet rs = stmt.executeQuery("Select * from `common` where `email` = '"+User_email.getUser_email()+"';");
                    rs.next();
                    int id = rs.getInt("c_id");
                    System.out.println("id: "+id);


                    sql = "Insert into `employee` values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    ps = conn.prepareStatement(sql);
                    ps.setInt(1,id);
                    ps.setString(2,EmployeeSignUp1_db.getFname());
                    ps.setString(3,EmployeeSignUp1_db.getLname());
                    ps.setString(4,EmployeeSignUp1_db.getDob());
                    ps.setString(5,EmployeeSignUp1_db.getGender());
                    ps.setString(6,EmployeeSignUp1_db.getTel());
                    ps.setString(7,EmployeeSignUp1_db.getAdd1());
                    ps.setString(8,EmployeeSignUp1_db.getAdd2());
                    ps.setString(9,EmployeeSignUp1_db.getCity());
                    ps.setString(10,EmployeeSignUp1_db.getState());
                    ps.setString(11,EmployeeSignUp1_db.getPin());
                    ps.setString(12,EmployeeSignUp2_db.getQualification());
                    ps.setString(13,EmployeeSignUp2_db.getInstitute());
                    ps.setString(14,EmployeeSignUp2_db.getDegreename());
                    ps.setString(15,EmployeeSignUp2_db.getYear());
                    ps.setString(16,EmployeeSignUp2_db.getScore());
                    ps.setString(17,ep2.getOrgname());
                    ps.setString(18,ep2.getJobtitle());
                    ps.setString(19,ep2.getJobloc());
                    if("".equals(workexp)) ps.setInt(20,0);
                    else ps.setInt(20,Integer.parseInt(ep2.getWorkexp()));
                    r = ps.executeUpdate();
                    if (r>0)System.out.println("\nSuccessful Employee entry!");
                    
                    EmployeeIndex.id = id;
                    EmployeeIndex ei = new EmployeeIndex();
                    ei.setVisible(true);
                    this.dispose();
                }catch(SQLException e){
                    System.err.println(e);
                }
                    }
                    else{
                        EmployeeSignUp3_error_label.setText(error);
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
        // TODO add your handling code here:
        EmployeeSignUp3_error_label.setText("");
    }//GEN-LAST:event_jButton2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSignUp3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeSignUp3_error_label;
    private javax.swing.JRadioButton EmployeeSignUp3_exp_radiobutton;
    private javax.swing.JTextField EmployeeSignUp3_jobloc_textfield;
    private javax.swing.JTextField EmployeeSignUp3_jobtitle_textfield;
    private javax.swing.JTextField EmployeeSignUp3_orgname_textfield;
    private javax.swing.JTextField EmployeeSignUp3_workexp_textfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
