/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import static Forms.EmployeeIndex.id;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.DBconnection;

/**
 *
 * @author USER
 */
public class EmployerIndex extends javax.swing.JFrame {

    static int id;

    /**
     * Creates new form EmployerIndex
     */
    
    public class User{
        public String jobtitle, sal, loc, exp, rec_tel, description;
        
        public User(String jobtitle, String sal, String loc, String exp, String description){
            this.jobtitle = jobtitle;
//            this.cname = cname;
            this.sal = sal;
            this.loc = loc;
            this.exp = exp;
            this.rec_tel = rec_tel;
            this.description = description;
        }     
    }
    
    public EmployerIndex() {
        initComponents();
        try{
            DBconnection connect = new DBconnection();
            Connection conn = connect.createConnection(); 
            Statement stmt = conn.createStatement();
            String query;
            String jobtitle, cname, sal, loc, exp, rec_tel, description;
            query = "Select * from `jobvacancy`";
            ResultSet rs = stmt.executeQuery(query);                       
                    
            ArrayList<User> list = new ArrayList<User>();                   
            while(rs.next()){
                jobtitle = rs.getString("jv_jobtitle");
                sal = rs.getString("jv_salary");
                loc = rs.getString("jv_location");
                exp = rs.getString("jv_experience");                
                description = rs.getString("description");                
                User u = new EmployerIndex.User(jobtitle, sal, loc, exp, description);
                list.add(u);
                u = null;
            }
            System.out.println("list sizeL "+list.size());
            if(list.isEmpty()){}//EmployerIndex_error_label.setText("No jobs available!");}
            else{
                DefaultTableModel model = (DefaultTableModel) EmployerIndex_job_jtable.getModel();
                Object rowData[] = new Object[5];
                for(int i = 0; i < list.size(); i++){
                    rowData[0] = list.get(i).jobtitle;
                    rowData[1] = list.get(i).sal;
                    rowData[2] = list.get(i).loc;
                    rowData[3] = list.get(i).exp;                    
                    rowData[4] = list.get(i).description;
                    model.addRow(rowData);
                }
            }
            rs.close();
            stmt.close();
            conn.close();
        }
        catch(SQLException e){
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmployerIndex_job_jtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("getHired!");
        jLabel1.setOpaque(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Create a Job!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        EmployerIndex_job_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JobTitle", "Salary", "Location", "Min. Experience", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        EmployerIndex_job_jtable.getTableHeader().setReorderingAllowed(false);
        EmployerIndex_job_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployerIndex_job_jtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EmployerIndex_job_jtable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CreateJob.id = id;
        CreateJob cj = new CreateJob();
        cj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EmployerIndex_job_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployerIndex_job_jtableMouseClicked
        // TODO add your handling code here:
        int index = EmployerIndex_job_jtable.getSelectedRow();
        TableModel mod = EmployerIndex_job_jtable.getModel();
        String jobtt = mod.getValueAt(index,0).toString();
        String sl = mod.getValueAt(index,1).toString();
        Object[] options1 = { "Delete!" };

        JPanel panel = new JPanel();
        panel.add(new JLabel("Delete job?"));
        

        int result = JOptionPane.showOptionDialog(null, panel, "Delete job!",
                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE,
                null, options1, null);
        if (result == JOptionPane.YES_OPTION){
            try{
            DBconnection connect = new DBconnection();
            Connection conn = connect.createConnection(); 
            Statement stmt = conn.createStatement();
                System.out.println(jobtt+sl);
            String query = "Delete from `jobvacancy` where jv_jobtitle = '"+jobtt+"' and jv_salary = '"+sl+"';";
                stmt.executeUpdate(query);
                System.out.println("Deleted successfully");
            }
            catch(SQLException e){
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_EmployerIndex_job_jtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployerIndex_job_jtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
