/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import models.EmployeeSignUp1_db;


/**
 *
 * @author astrodist
 */
public class EmployeeSignUp1 extends javax.swing.JFrame {

    


    /**
     * Creates new form Employee
     */
    public EmployeeSignUp1() {
        this.setTitle("Employee SignUp Form 1");
        initComponents();
    }
    static EmployeeSignUp1_db ep;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        EmployeeSignUp1_fname_textfield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmployeeSignUp1_lname_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmployeeSignUp1_state_textfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmployeeSignUp1_city_textfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmployeeSignUp1_pin_textfield = new javax.swing.JTextField();
        EmployeeSignUp1_tel_textfield = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        EmployeeSignUp1_male_rbutton = new javax.swing.JRadioButton();
        EmployeeSignUp1_female_rbutton = new javax.swing.JRadioButton();
        EmployeeSignUp1_others_rbutton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EmployeeSignUp1_add1_textfield = new javax.swing.JTextField();
        EmployeeSignUp1_add2_textfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        EmployeeSignUp_error_label = new javax.swing.JLabel();
        EmployeeSignUp1_error_label = new javax.swing.JLabel();
        EmployeeSignUp1_dob_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        EmployeeSignUp1_fname_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_fname_textfield.setToolTipText("");
        EmployeeSignUp1_fname_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp1_fname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_fname_textfieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("First Name:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Last Name:");
        jLabel2.setToolTipText("");

        EmployeeSignUp1_lname_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_lname_textfield.setToolTipText("");
        EmployeeSignUp1_lname_textfield.setActionCommand("<Not Set>");

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 40)); // NOI18N
        jLabel3.setText(" Personal Details");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel4.setText("Date of Birth:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel5.setText("Contact Number:");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel6.setText("City:");
        jLabel6.setToolTipText("");

        EmployeeSignUp1_state_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_state_textfield.setToolTipText("");
        EmployeeSignUp1_state_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp1_state_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_state_textfieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel7.setText("Address:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel8.setText("State:");
        jLabel8.setToolTipText("");

        EmployeeSignUp1_city_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_city_textfield.setToolTipText("");
        EmployeeSignUp1_city_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp1_city_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_city_textfieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel9.setText("Pin code:");
        jLabel9.setToolTipText("");

        EmployeeSignUp1_pin_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_pin_textfield.setToolTipText("");
        EmployeeSignUp1_pin_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp1_pin_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_pin_textfieldActionPerformed(evt);
            }
        });

        EmployeeSignUp1_tel_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_tel_textfield.setToolTipText("");
        EmployeeSignUp1_tel_textfield.setActionCommand("<Not Set>");
        EmployeeSignUp1_tel_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_tel_textfieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel11.setText("Gender:");
        jLabel11.setToolTipText("");

        buttonGroup1.add(EmployeeSignUp1_male_rbutton);
        EmployeeSignUp1_male_rbutton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        EmployeeSignUp1_male_rbutton.setText("Male");
        EmployeeSignUp1_male_rbutton.setOpaque(false);

        buttonGroup1.add(EmployeeSignUp1_female_rbutton);
        EmployeeSignUp1_female_rbutton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        EmployeeSignUp1_female_rbutton.setText("Female");
        EmployeeSignUp1_female_rbutton.setOpaque(false);

        buttonGroup1.add(EmployeeSignUp1_others_rbutton);
        EmployeeSignUp1_others_rbutton.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        EmployeeSignUp1_others_rbutton.setText("Non - binary");
        EmployeeSignUp1_others_rbutton.setOpaque(false);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setText("Line Number 1:");
        jLabel12.setToolTipText("");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setText("Line Number 2:");
        jLabel13.setToolTipText("");

        EmployeeSignUp1_add1_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_add1_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_add1_textfieldActionPerformed(evt);
            }
        });

        EmployeeSignUp1_add2_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployeeSignUp1_add2_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_add2_textfieldActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(240, 240, 240));
        jButton3.setText("Submit");
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton3FocusLost(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("GetHired Immediately!");
        jLabel14.setOpaque(true);

        EmployeeSignUp_error_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmployeeSignUp_error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        EmployeeSignUp1_error_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmployeeSignUp1_error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        EmployeeSignUp1_dob_textfield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmployeeSignUp1_dob_textfield.setText("dd/mm/yyyy");
        EmployeeSignUp1_dob_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmployeeSignUp1_dob_textfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmployeeSignUp1_dob_textfieldFocusLost(evt);
            }
        });
        EmployeeSignUp1_dob_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeSignUp1_dob_textfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EmployeeSignUp1_city_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EmployeeSignUp1_state_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(EmployeeSignUp1_pin_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(EmployeeSignUp1_add1_textfield)
                                .addComponent(EmployeeSignUp1_add2_textfield)
                                .addComponent(EmployeeSignUp1_error_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7)
                            .addComponent(EmployeeSignUp1_tel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmployeeSignUp_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(EmployeeSignUp1_fname_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(EmployeeSignUp1_dob_textfield))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(EmployeeSignUp1_lname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(EmployeeSignUp1_male_rbutton)
                                        .addGap(18, 18, 18)
                                        .addComponent(EmployeeSignUp1_female_rbutton)
                                        .addGap(18, 18, 18)
                                        .addComponent(EmployeeSignUp1_others_rbutton)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeSignUp1_lname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeSignUp1_fname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeSignUp1_male_rbutton)
                    .addComponent(EmployeeSignUp1_female_rbutton)
                    .addComponent(EmployeeSignUp1_others_rbutton)
                    .addComponent(EmployeeSignUp1_dob_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp1_tel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp1_add1_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeSignUp1_add2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeSignUp1_pin_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeSignUp1_state_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeSignUp1_city_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EmployeeSignUp1_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeSignUp_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String fname, lname, dob, tel, add1, add2, city, state, pin, gender = "", error = "";
        int selection = 0;
        if(EmployeeSignUp1_male_rbutton.isSelected() || EmployeeSignUp1_female_rbutton.isSelected() || EmployeeSignUp1_others_rbutton.isSelected()){
            if(EmployeeSignUp1_male_rbutton.isSelected()){
                gender = "male";
            }
            else if(EmployeeSignUp1_female_rbutton.isSelected()){
                gender = "female";
            }
            else{
                gender = "non-binary";
            }
            selection = 1;
        }
        
                fname = EmployeeSignUp1_fname_textfield.getText();
                lname = EmployeeSignUp1_lname_textfield.getText();
                dob = EmployeeSignUp1_dob_textfield.getText();
                tel = EmployeeSignUp1_tel_textfield.getText();
                add1 = EmployeeSignUp1_add1_textfield.getText();
                add2 = EmployeeSignUp1_add2_textfield.getText();
                city = EmployeeSignUp1_city_textfield.getText();
                state = EmployeeSignUp1_state_textfield.getText();
                pin = EmployeeSignUp1_pin_textfield.getText();                                
                
                boolean numeric1 = true;
                try {
                    Double num1 = Double.parseDouble(tel);  //tel
                } catch (NumberFormatException e) {
                    numeric1 = false;
                }
                
                boolean numeric2 = true;
                try {
                    Double num2 = Double.parseDouble(pin); //pin
                } catch (NumberFormatException e) {
                    numeric2 = false;
                }
                
                //Special Characters
                Pattern my_pattern1 = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
                Matcher my_match1 = my_pattern1.matcher(add1);
                boolean check1 = my_match1.find();

                Pattern my_pattern2 = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
                Matcher my_match2 = my_pattern2.matcher(add2);
                boolean check2 = my_match1.find();
                
                //Dob
                String arr[] = dob.split("/");
                dob = arr[0]+arr[1]+arr[2];
                boolean numeric3 = true;  //dd
                try {
                    Double num3 = Double.parseDouble(arr[0]);
                } catch (NumberFormatException e) {
                    numeric3 = false;
                }
                
                boolean numeric4 = true;
                try {
                    Double num4 = Double.parseDouble(arr[1]); //mm
                } catch (NumberFormatException e) {
                    numeric4 = false;
                }
                
                boolean numeric5 = true;
                try {
                    Double num5 = Double.parseDouble(arr[2]);//yyyy
                } catch (NumberFormatException e) {
                    numeric5 = false;
                }
                                                                                                
                if(fname.isEmpty() || lname.isEmpty() || dob.isEmpty() || tel.isEmpty() || add1.isEmpty() || add2.isEmpty() || state.isEmpty() || pin.isEmpty()){
                    error = "Please enter details in all fields";
                }
                else if(selection == 0){
                    error = "Select your gender";
                }
                else if(!(fname.matches("^[a-zA-Z]*$"))){
                    error = "Please enter valid first name";
                }
                else if((!lname.equals("")) && !(lname.matches("^[a-zA-Z]*$"))){
                    error = "Please enter valid last name";
                }
                else if(numeric1 == false){
                    error = "Please enter valid contact number";
                }
                else if(check1){
                   error = "Special symbols in address line 1 are not allowed!";
                }
                else if(check2){
                    error = "Special symbols in address line 2 are not allowed!";
                }
                else if(numeric2 == false || pin.length()<6){
                   error = "Enter valid pincode";
                }
                else if(numeric3 == false || numeric4 == false || numeric5 == false){
                    error = "Enter valid date of birth";
                }
                
                if(error.isEmpty()){
                    EmployeeSignUp1_db ep = new EmployeeSignUp1_db(fname, lname, dob, tel, add1, add2, city, gender, state, pin);
                    
                    EmployeeSignUp3.EmployeeSignUp1_db = ep;
                    EmployeeSignUp2 sp = new EmployeeSignUp2();
                    sp.setVisible(true);
                    this.dispose();
                }
                else{
                    EmployeeSignUp1_error_label.setText(error);
                }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SignUp sp = new SignUp();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EmployeeSignUp1_add2_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_add2_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_add2_textfieldActionPerformed

    private void EmployeeSignUp1_add1_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_add1_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_add1_textfieldActionPerformed

    private void EmployeeSignUp1_tel_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_tel_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_tel_textfieldActionPerformed

    private void EmployeeSignUp1_pin_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_pin_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_pin_textfieldActionPerformed

    private void EmployeeSignUp1_city_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_city_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_city_textfieldActionPerformed

    private void EmployeeSignUp1_state_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_state_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_state_textfieldActionPerformed

    private void EmployeeSignUp1_fname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_fname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_fname_textfieldActionPerformed

    private void jButton3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusLost
        // TODO add your handling code here:
        EmployeeSignUp1_error_label.setText("");
    }//GEN-LAST:event_jButton3FocusLost

    private void EmployeeSignUp1_dob_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_dob_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeSignUp1_dob_textfieldActionPerformed

    private void EmployeeSignUp1_dob_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_dob_textfieldFocusGained
        // TODO add your handling code here:
        EmployeeSignUp1_dob_textfield.setText("");
    }//GEN-LAST:event_EmployeeSignUp1_dob_textfieldFocusGained

    private void EmployeeSignUp1_dob_textfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmployeeSignUp1_dob_textfieldFocusLost
        // TODO add your handling code here:        
    }//GEN-LAST:event_EmployeeSignUp1_dob_textfieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSignUp1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmployeeSignUp1_add1_textfield;
    private javax.swing.JTextField EmployeeSignUp1_add2_textfield;
    private javax.swing.JTextField EmployeeSignUp1_city_textfield;
    private javax.swing.JTextField EmployeeSignUp1_dob_textfield;
    private javax.swing.JLabel EmployeeSignUp1_error_label;
    private javax.swing.JRadioButton EmployeeSignUp1_female_rbutton;
    private javax.swing.JTextField EmployeeSignUp1_fname_textfield;
    private javax.swing.JTextField EmployeeSignUp1_lname_textfield;
    private javax.swing.JRadioButton EmployeeSignUp1_male_rbutton;
    private javax.swing.JRadioButton EmployeeSignUp1_others_rbutton;
    private javax.swing.JTextField EmployeeSignUp1_pin_textfield;
    private javax.swing.JTextField EmployeeSignUp1_state_textfield;
    private javax.swing.JTextField EmployeeSignUp1_tel_textfield;
    private javax.swing.JLabel EmployeeSignUp_error_label;
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
