/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import static Forms.SignUp.um;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import models.EmployerSignUp1_dbclass;
import models.*;


/**
 *
 * @author astrodist
 */
public class EmployerSignUp1 extends javax.swing.JFrame {

    

    


    /**
     * Creates new form EmployerSignUp1
     */
    public EmployerSignUp1() {
        this.setTitle("Employer SignUp Form");
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmpSignUp1_gst_textfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        EmpSignUp1_name_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EmpSignUp1_tel_textfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EmpSignUp1_add2_textfield = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        EmpSignUp1_add1_textfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        EmpSignUp1_city_textfield = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        EmpSignUp1_state_textfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EmpSignUp1_pin_textfield = new javax.swing.JTextField();
        EmployerSignUp1_error_label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("HireHere!");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 40)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText(" Company Details");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("Name:");
        jLabel1.setToolTipText("");

        EmpSignUp1_gst_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_gst_textfield.setToolTipText("");
        EmpSignUp1_gst_textfield.setActionCommand("<Not Set>");
        EmpSignUp1_gst_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSignUp1_gst_textfieldFocusGained(evt);
            }
        });
        EmpSignUp1_gst_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSignUp1_gst_textfieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Telephone Number");
        jLabel2.setToolTipText("");

        EmpSignUp1_name_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_name_textfield.setToolTipText("");
        EmpSignUp1_name_textfield.setActionCommand("<Not Set>");
        EmpSignUp1_name_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSignUp1_name_textfieldFocusGained(evt);
            }
        });
        EmpSignUp1_name_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSignUp1_name_textfieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel4.setText("GST Number:");
        jLabel4.setToolTipText("");

        EmpSignUp1_tel_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_tel_textfield.setToolTipText("");
        EmpSignUp1_tel_textfield.setActionCommand("<Not Set>");
        EmpSignUp1_tel_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSignUp1_tel_textfieldFocusGained(evt);
            }
        });
        EmpSignUp1_tel_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSignUp1_tel_textfieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel7.setText("Address:");
        jLabel7.setToolTipText("");

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel12.setText("Line Number 1:");
        jLabel12.setToolTipText("");

        EmpSignUp1_add2_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_add2_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSignUp1_add2_textfieldFocusGained(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jLabel13.setText("Line Number 2:");
        jLabel13.setToolTipText("");

        EmpSignUp1_add1_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_add1_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSignUp1_add1_textfieldFocusGained(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.black);
        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jButton2.setText("Next");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.black);
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setLabel("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel6.setText("City:");
        jLabel6.setToolTipText("");

        EmpSignUp1_city_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_city_textfield.setToolTipText("");
        EmpSignUp1_city_textfield.setActionCommand("<Not Set>");
        EmpSignUp1_city_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSignUp1_city_textfieldFocusGained(evt);
            }
        });
        EmpSignUp1_city_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSignUp1_city_textfieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel8.setText("State:");
        jLabel8.setToolTipText("");

        EmpSignUp1_state_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_state_textfield.setToolTipText("");
        EmpSignUp1_state_textfield.setActionCommand("<Not Set>");
        EmpSignUp1_state_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmpSignUp1_state_textfieldFocusGained(evt);
            }
        });
        EmpSignUp1_state_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSignUp1_state_textfieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel9.setText("Pin code:");
        jLabel9.setToolTipText("");

        EmpSignUp1_pin_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmpSignUp1_pin_textfield.setToolTipText("");
        EmpSignUp1_pin_textfield.setActionCommand("<Not Set>");
        EmpSignUp1_pin_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpSignUp1_pin_textfieldActionPerformed(evt);
            }
        });

        EmployerSignUp1_error_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("HireHere!");
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployerSignUp1_error_label)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(280, 280, 280)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpSignUp1_add2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel7)
                                    .addComponent(EmpSignUp1_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(EmpSignUp1_add1_textfield, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(EmpSignUp1_gst_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addGap(134, 134, 134)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(EmpSignUp1_tel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(EmpSignUp1_city_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmpSignUp1_state_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(EmpSignUp1_pin_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpSignUp1_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpSignUp1_gst_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpSignUp1_tel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpSignUp1_add1_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmpSignUp1_add2_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmpSignUp1_city_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpSignUp1_state_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpSignUp1_pin_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(EmployerSignUp1_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmpSignUp1_pin_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSignUp1_pin_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpSignUp1_pin_textfieldActionPerformed

    private void EmpSignUp1_state_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSignUp1_state_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpSignUp1_state_textfieldActionPerformed

    private void EmpSignUp1_state_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSignUp1_state_textfieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpSignUp1_state_textfieldFocusGained

    private void EmpSignUp1_city_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSignUp1_city_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpSignUp1_city_textfieldActionPerformed

    private void EmpSignUp1_city_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSignUp1_city_textfieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpSignUp1_city_textfieldFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignUp sp = new SignUp();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String name, gst, add1, add2, city, state, tel, pin, error = "";

        name = EmpSignUp1_name_textfield.getText();
        gst = EmpSignUp1_gst_textfield.getText();
        add1 = EmpSignUp1_add1_textfield.getText();
        add2 = EmpSignUp1_add2_textfield.getText();
        city = EmpSignUp1_city_textfield.getText();
        state = EmpSignUp1_state_textfield.getText();
        tel = EmpSignUp1_tel_textfield.getText();
        pin = EmpSignUp1_pin_textfield.getText();

        //Special Characters
        Pattern my_pattern1 = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
        Matcher my_match1 = my_pattern1.matcher(add1);
        boolean check1 = my_match1.find();

        Pattern my_pattern2 = Pattern.compile("[^a-z0-9 ]", Pattern.CASE_INSENSITIVE);
        Matcher my_match2 = my_pattern2.matcher(add2);
        boolean check2 = my_match1.find();

        //Numeric string
        boolean numeric1 = true;
        try {
            Double num1 = Double.parseDouble(tel);
        } catch (NumberFormatException e) {
            numeric1 = false;
        }

        boolean numeric2 = true;
        try {
            Double num2 = Double.parseDouble(pin);
        } catch (NumberFormatException e) {
            numeric2 = false;
        }

        if(name.isEmpty() || gst.isEmpty() || add1.isEmpty() || add2.isEmpty() || city.isEmpty() || state.isEmpty() || tel.isEmpty() || pin.isEmpty()){
            error = "Please enter all fields!";
        }
        else if((gst.matches("^[a-zA-Z0-9]*$")) == false || gst.length()<15){
            error = "Enter correct GST number";
        }
        else if(numeric1 == false || tel.length()<10){
            error = "Enter valid contact number";
        }
        else if(check1){
            error = "Special symbols in address line 1 are not allowed!";
        }
        else if(check2){
            error = "Special symbols in address line 2 are not allowed!";
        }
        else if(numeric2 == false || pin.length()<6){
            error = "Enter valid pincode";
        }

        if(error.isEmpty()){
           
            EmployerSignUp1_dbclass ep = new EmployerSignUp1_dbclass(name, gst, add1, add2, city, state, tel, pin);            
            EmployerSignUp2.EmployerSignUp1_dbclass = ep;
            EmployerSignUp2 sp = new EmployerSignUp2();
            sp.setVisible(true);
            this.dispose();
        }
        else{
            EmployerSignUp1_error_label.setText(error);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
        // TODO add your handling code here:
        EmployerSignUp1_error_label.setText("");
    }//GEN-LAST:event_jButton2FocusLost

    private void EmpSignUp1_add1_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSignUp1_add1_textfieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpSignUp1_add1_textfieldFocusGained

    private void EmpSignUp1_add2_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSignUp1_add2_textfieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpSignUp1_add2_textfieldFocusGained

    private void EmpSignUp1_tel_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSignUp1_tel_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpSignUp1_tel_textfieldActionPerformed

    private void EmpSignUp1_tel_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSignUp1_tel_textfieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpSignUp1_tel_textfieldFocusGained

    private void EmpSignUp1_name_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSignUp1_name_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpSignUp1_name_textfieldActionPerformed

    private void EmpSignUp1_name_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSignUp1_name_textfieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpSignUp1_name_textfieldFocusGained

    private void EmpSignUp1_gst_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpSignUp1_gst_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpSignUp1_gst_textfieldActionPerformed

    private void EmpSignUp1_gst_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmpSignUp1_gst_textfieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_EmpSignUp1_gst_textfieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerSignUp1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmpSignUp1_add1_textfield;
    private javax.swing.JTextField EmpSignUp1_add2_textfield;
    private javax.swing.JTextField EmpSignUp1_city_textfield;
    private javax.swing.JTextField EmpSignUp1_gst_textfield;
    private javax.swing.JTextField EmpSignUp1_name_textfield;
    private javax.swing.JTextField EmpSignUp1_pin_textfield;
    private javax.swing.JTextField EmpSignUp1_state_textfield;
    private javax.swing.JTextField EmpSignUp1_tel_textfield;
    private javax.swing.JLabel EmployerSignUp1_error_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
