/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import utils.DBconnection;

/**
 *
 * @author USER
 */
public class EmployeeIndex extends javax.swing.JFrame {

    static int id;

    

    
    /**
     * Creates new form EmployeeIndex
     */
    public class User{
        public String jobtitle, sal, loc, exp, rec_tel, description;
        
        public User(String jobtitle, String sal, String loc, String exp,String rec_tel, String description){
            this.jobtitle = jobtitle;
//            this.cname = cname;
            this.sal = sal;
            this.loc = loc;
            this.exp = exp;
            this.rec_tel = rec_tel;
            this.description = description;
        }
    }    
    
    public EmployeeIndex() {
        initComponents();
        
        try{
            DBconnection connect = new DBconnection();
            Connection conn = connect.createConnection(); 
            Statement stmt = conn.createStatement();
            String query;
            String jobtitle, cname, sal, loc, exp, rec_tel, description;
            query = "Select * from `jobvacancy` where `jv_degree` = (Select `employee_degree` from `employee` where employee_id = " + id +");";
            ResultSet rs = stmt.executeQuery(query);                       
                    
            ArrayList<User> list = new ArrayList<User>();                   
            while(rs.next()){
                jobtitle = rs.getString("jv_jobtitle");
//                cname = rs.getString("");
                sal = rs.getString("jv_salary");
                loc = rs.getString("jv_location");
                exp = rs.getString("jv_experience");
                rec_tel = rs.getString("rec_tel");
                description = rs.getString("description");                
                User u = new User(jobtitle, sal, loc, exp, rec_tel, description);
                list.add(u);
                u = null;
            }
            System.out.println("list sizeL "+list.size());
            if(list.isEmpty()){EmployeeIndex_error_label.setText("No jobs available!");}
            else{
                DefaultTableModel model = (DefaultTableModel) EmployeeIndex_job_jtable.getModel();
                Object rowData[] = new Object[6];
                for(int i = 0; i < list.size(); i++){
                    rowData[0] = list.get(i).jobtitle;
                    rowData[1] = list.get(i).sal;
                    rowData[2] = list.get(i).loc;
                    rowData[3] = list.get(i).exp;
                    rowData[4] = list.get(i).rec_tel;
                    rowData[5] = list.get(i).description;
                    model.addRow(rowData);
                }
            }
            ///////////////////////////////////////////////////////////////////////////////////////////////////
           
            ///////////////////////////////////////////////////////////////////////////////////////////////////
         
        }
        catch(SQLException e){
            System.err.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        EmployeeIndex_job_jtable = new javax.swing.JTable();
        EmployeeIndex_error_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("getHired!");
        jLabel1.setOpaque(true);

        EmployeeIndex_job_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "JobTitle", "Salary", "Location", "Min. Experience", "Contact no.", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        EmployeeIndex_job_jtable.getTableHeader().setReorderingAllowed(false);
        EmployeeIndex_job_jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeeIndex_job_jtableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EmployeeIndex_job_jtable);

        EmployeeIndex_error_label.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EmployeeIndex_error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addComponent(EmployeeIndex_error_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeIndex_error_label, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeIndex_job_jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeIndex_job_jtableMouseClicked
        // TODO add your handling code here:            
    }//GEN-LAST:event_EmployeeIndex_job_jtableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeIndex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeIndex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EmployeeIndex_error_label;
    private javax.swing.JTable EmployeeIndex_job_jtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
