/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import models.*;
import utils.DBconnection;



/**
 *
 * @author astrodist
 */
public class EmployerSignUp2 extends javax.swing.JFrame {

    static User_email User_email;
    static EmployerSignUp1_dbclass EmployerSignUp1_dbclass;
    

    /**
     * Creates new form EmployerSignUp2
     */
    public EmployerSignUp2() {
        this.setTitle("Employer SignUp Form 2");
        initComponents();
//        EmployerSignUp2_error_label.setText(EmployerSignUp1_dbclass.getCity());
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmployerSignUp2_jobtitle_textfield = new javax.swing.JTextField();
        EmployerSignUp2_hireexp_textfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        EmployerSignUp2_fname_textfield = new javax.swing.JTextField();
        EmployerSignUp2_lname_textfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        EmployerSignUp2_tel_textfield = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        EmployerSignUp2_email_textfield = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        EmployerSignUp2_error_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);

        jLabel3.setBackground(java.awt.Color.black);
        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 40)); // NOI18N
        jLabel3.setText(" Recruiter Details");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel1.setText("First Name:");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel2.setText("Last Name:");
        jLabel2.setToolTipText("");

        EmployerSignUp2_jobtitle_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployerSignUp2_jobtitle_textfield.setToolTipText("");
        EmployerSignUp2_jobtitle_textfield.setActionCommand("<Not Set>");
        EmployerSignUp2_jobtitle_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployerSignUp2_jobtitle_textfieldActionPerformed(evt);
            }
        });

        EmployerSignUp2_hireexp_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployerSignUp2_hireexp_textfield.setToolTipText("");
        EmployerSignUp2_hireexp_textfield.setActionCommand("<Not Set>");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel4.setText("Hiring Experience:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel5.setText("Job Title:");
        jLabel5.setToolTipText("");

        EmployerSignUp2_fname_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployerSignUp2_fname_textfield.setToolTipText("");
        EmployerSignUp2_fname_textfield.setActionCommand("<Not Set>");
        EmployerSignUp2_fname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployerSignUp2_fname_textfieldActionPerformed(evt);
            }
        });

        EmployerSignUp2_lname_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployerSignUp2_lname_textfield.setToolTipText("");
        EmployerSignUp2_lname_textfield.setActionCommand("<Not Set>");
        EmployerSignUp2_lname_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployerSignUp2_lname_textfieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel6.setText("Contact Number:");
        jLabel6.setToolTipText("");

        EmployerSignUp2_tel_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployerSignUp2_tel_textfield.setToolTipText("");
        EmployerSignUp2_tel_textfield.setActionCommand("<Not Set>");
        EmployerSignUp2_tel_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployerSignUp2_tel_textfieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel7.setText("Email:");
        jLabel7.setToolTipText("");

        EmployerSignUp2_email_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        EmployerSignUp2_email_textfield.setToolTipText("");
        EmployerSignUp2_email_textfield.setActionCommand("<Not Set>");

        jButton2.setBackground(java.awt.Color.black);
        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jButton2.setForeground(new java.awt.Color(240, 240, 240));
        jButton2.setText("Next");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButton2FocusLost(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.black);
        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 25)); // NOI18N
        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setLabel("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("KeepHiring!");
        jLabel8.setOpaque(true);

        EmployerSignUp2_error_label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EmployerSignUp2_error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployerSignUp2_jobtitle_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(EmployerSignUp2_fname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(EmployerSignUp2_tel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EmployerSignUp2_email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(EmployerSignUp2_hireexp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(EmployerSignUp2_lname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(EmployerSignUp2_error_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployerSignUp2_fname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployerSignUp2_lname_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployerSignUp2_jobtitle_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployerSignUp2_hireexp_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployerSignUp2_tel_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployerSignUp2_email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EmployerSignUp2_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployerSignUp2_jobtitle_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployerSignUp2_jobtitle_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployerSignUp2_jobtitle_textfieldActionPerformed

    private void EmployerSignUp2_fname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployerSignUp2_fname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployerSignUp2_fname_textfieldActionPerformed

    private void EmployerSignUp2_tel_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployerSignUp2_tel_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployerSignUp2_tel_textfieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EmployerSignUp1 sp = new EmployerSignUp1();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void EmployerSignUp2_lname_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployerSignUp2_lname_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployerSignUp2_lname_textfieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String fname, lname, hireexp, jobtitle, tel, email;
        fname = EmployerSignUp2_fname_textfield.getText();
        lname = EmployerSignUp2_lname_textfield.getText();
        hireexp = EmployerSignUp2_hireexp_textfield.getText();
        jobtitle = EmployerSignUp2_jobtitle_textfield.getText();
        tel = EmployerSignUp2_tel_textfield.getText();
        email = EmployerSignUp2_email_textfield.getText();
        String error = "";
        
        //check numeric
        boolean numeric1 = true;
        try {
            Double num1 = Double.parseDouble(tel);
        } catch (NumberFormatException e) {
            numeric1 = false;
        }
        
        boolean numeric2 = true;
        try {
            Double num2 = Double.parseDouble(hireexp);
        } catch (NumberFormatException e) {
            numeric2 = false;
        }
        
        if(fname.isEmpty() || lname.isEmpty() || hireexp.isEmpty() || jobtitle.isEmpty() || tel.isEmpty() || email.isEmpty()){
            error = "Please enter details in all fields";
        }
        else if((!fname.equals("")) && (!fname.matches("^[a-zA-Z]*$"))){
            error = "Please enter valid first name";
        }
        else if((!jobtitle.equals("")) && (!jobtitle.matches("^[a-zA-Z]*$"))){
            error = "Please enter valid jobtitle name";
        }
        else if((!lname.equals("")) && (!lname.matches("^[a-zA-Z]*$"))){
            error = "Please enter valid last name";
        }
        else if(!numeric2){
            error = "Please enter a numeric value in your hiring experience!";
        }
        else if(!numeric1){
            error = "Please enter a valid contact number";
        }
        else if(email.contains("@") == false || email.contains(".") == false){
            error = "Enter valid email";
        }
        
        if(error.isEmpty()){
            EmployerSignUp2_dbclass ep2 = new EmployerSignUp2_dbclass(fname, lname, hireexp, jobtitle, tel, email);
            try{
                    DBconnection connect = new DBconnection();
                    Connection conn = connect.createConnection(); 
                    Statement stmt = conn.createStatement();

                    String sql = "INSERT INTO `common` (email, password, flag)VALUES (?,?,?)";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, User_email.getUser_email());
                    ps.setString(2, User_email.getUser_password());
                    ps.setInt(3,1);
                    int r = ps.executeUpdate();
                    if (r>0)System.out.println("\nSuccessful User-email entry for employer!");
                    
//                    try{
                    String query = "Select * from `common` where `email` = '"+User_email.getUser_email()+"';";
                    ResultSet rs = stmt.executeQuery(query);
                    rs.next();
                    int id = rs.getInt("c_id");
                    System.out.println("id: "+id);
//                    }catch (SQLException e) {
                    // TODO Auto-generated catch block
//                         e.printStackTrace();
//                    }
                    
//                    try{
                    sql = "Insert into `employer`(employer_id,employer_name,gstno,telno,employer_address1,employer_address2,employer_city,employer_state,employer_pincode,recruiter_fname,recruiter_lname,recruiter_jobtitle,recruiter_experience,recruiter_contactno,recruiter_email) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    ps = conn.prepareStatement(sql);
                    ps.setInt(1,id);
                    ps.setString(2,EmployerSignUp1_dbclass.getName());
                    ps.setString(3,EmployerSignUp1_dbclass.getGst());
                    ps.setString(4,EmployerSignUp1_dbclass.getTel());
                    ps.setString(5,EmployerSignUp1_dbclass.getAdd1());
                    ps.setString(6,EmployerSignUp1_dbclass.getAdd2());
                    ps.setString(7,EmployerSignUp1_dbclass.getCity());
                    ps.setString(8,EmployerSignUp1_dbclass.getState());
                    ps.setString(9,EmployerSignUp1_dbclass.getPin());
                    ps.setString(10,ep2.getFname());
                    ps.setString(11,ep2.getLname());
                    ps.setString(12,ep2.getJobtitle());
                    ps.setString(13,ep2.getHireexp());
                    ps.setString(14,ep2.getTel());
                    ps.setString(15,ep2.getEmail());
                    r = ps.executeUpdate();
                    if (r>0)System.out.println("\nSuccessful Employer entry!");
//                    }catch (SQLException e) {
                       // TODO Auto-generated catch block
//                        e.printStackTrace();
//                    }
                    EmployerIndex ei = new EmployerIndex();
                    ei.setVisible(true);
                    this.dispose();
                    
                }catch(SQLException e){
                    System.err.println(e);
                }  
        }
        else{
            EmployerSignUp2_error_label.setText(error);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusLost
        // TODO add your handling code here:
        EmployerSignUp2_error_label.setText("");
    }//GEN-LAST:event_jButton2FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployerSignUp2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployerSignUp2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmployerSignUp2_email_textfield;
    private javax.swing.JLabel EmployerSignUp2_error_label;
    private javax.swing.JTextField EmployerSignUp2_fname_textfield;
    private javax.swing.JTextField EmployerSignUp2_hireexp_textfield;
    private javax.swing.JTextField EmployerSignUp2_jobtitle_textfield;
    private javax.swing.JTextField EmployerSignUp2_lname_textfield;
    private javax.swing.JTextField EmployerSignUp2_tel_textfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
