/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import models.User_email;

/**
 *
 * @author astrodist
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
        
    }
    static User_email um;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SignUp_email_textfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SignUp_password_textfield = new javax.swing.JPasswordField();
        SignUp_Employee = new javax.swing.JRadioButton();
        SignUp_Employer = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SignUp_repassword_textfield = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        SignUp_error_label = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SignUp ");

        jPanel1.setBackground(java.awt.Color.white);

        jPanel2.setBackground(java.awt.Color.black);
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 50)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Sign-up");
        jLabel2.setToolTipText("");

        SignUp_email_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        SignUp_email_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_email_textfieldFocusGained(evt);
            }
        });
        SignUp_email_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_email_textfieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Enter Email:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Enter Password:");

        SignUp_password_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        SignUp_password_textfield.setToolTipText("");
        SignUp_password_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_password_textfieldFocusGained(evt);
            }
        });
        SignUp_password_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignUp_password_textfieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(SignUp_Employee);
        SignUp_Employee.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        SignUp_Employee.setForeground(java.awt.Color.white);
        SignUp_Employee.setText("Employee");
        SignUp_Employee.setOpaque(false);
        SignUp_Employee.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_EmployeeFocusGained(evt);
            }
        });

        buttonGroup1.add(SignUp_Employer);
        SignUp_Employer.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        SignUp_Employer.setForeground(java.awt.Color.white);
        SignUp_Employer.setText("Employer");
        SignUp_Employer.setOpaque(false);
        SignUp_Employer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_EmployerFocusGained(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.lightGray);
        jButton2.setFont(new java.awt.Font("Arial", 0, 25)); // NOI18N
        jButton2.setText("Submit");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Already have an account? Sign-in");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        SignUp_repassword_textfield.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        SignUp_repassword_textfield.setToolTipText("");
        SignUp_repassword_textfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SignUp_repassword_textfieldFocusGained(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Re-enter Password:");

        SignUp_error_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SignUp_error_label.setForeground(new java.awt.Color(240, 240, 240));
        SignUp_error_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignUp_Employee)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(SignUp_email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SignUp_password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(87, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(SignUp_repassword_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SignUp_Employer)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SignUp_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUp_email_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUp_password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SignUp_repassword_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SignUp_Employee)
                    .addComponent(SignUp_Employer))
                .addGap(18, 18, 18)
                .addComponent(SignUp_error_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 70)); // NOI18N
        jLabel1.setText("GetHired");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 200));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SignIn sp = new SignIn();
        sp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SignUp_password_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_password_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_password_textfieldActionPerformed

    private void SignUp_email_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignUp_email_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignUp_email_textfieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        int selection = 0;
        if(SignUp_Employee.isSelected() || SignUp_Employer.isSelected()){
            selection = 1;
        }
        
        String signup_email = SignUp_email_textfield.getText();
        String signup_password = SignUp_password_textfield.getText();
        String signup_repassword = SignUp_repassword_textfield.getText();
        String error = "";
        if(selection == 0){
            error = "Please select either Employee or Employer";
        }
        else if(signup_email.isEmpty()){
            error = "Please enter email!";
        }
        else if(signup_email.contains("@") == false || signup_email.contains(".") == false){
            error = "Please enter correct email containing '@' and '.'";
        }
        else if(signup_password.isEmpty()){
            error = "Please enter password!";
        }
        else if(signup_repassword.isEmpty()){
            error = "Please enter re-enter password!";
        }
        else if(signup_password.length() < 8){
            error = "Please enter valid password with atleast 8 characters";
        }
        else if(signup_password == null ? signup_repassword != null : !signup_password.equals(signup_repassword)){
            error = "Please enter same passwords";
        }
        
        if(error.isEmpty()){
            if(SignUp_Employee.isSelected() == true){
                
                User_email um = new User_email();
                um.setUser_email(signup_email);
                um.setUser_password(signup_password);
                um.setUser_employee_0_employer_1("Employee");
                
                EmployeeSignUp1 sp = new EmployeeSignUp1();
                EmployeeSignUp3.User_email = um;
                sp.setVisible(true);
                this.dispose();
            }
            else{
                User_email um = new User_email();
                um.setUser_email(signup_email);
                um.setUser_password(signup_password);
                um.setUser_employee_0_employer_1("Employer");
                                
                EmployerSignUp1 sp = new EmployerSignUp1();
                EmployerSignUp2.User_email = um;
                sp.setVisible(true);
                this.dispose();
            }   
        }
        else{
            SignUp_error_label.setText(error);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SignUp_email_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_email_textfieldFocusGained
        // TODO add your handling code here:
        SignUp_error_label.setText("");
    }//GEN-LAST:event_SignUp_email_textfieldFocusGained

    private void SignUp_password_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_password_textfieldFocusGained
        // TODO add your handling code here:
        SignUp_error_label.setText("");
    }//GEN-LAST:event_SignUp_password_textfieldFocusGained

    private void SignUp_repassword_textfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_repassword_textfieldFocusGained
        // TODO add your handling code here:
        SignUp_error_label.setText("");
    }//GEN-LAST:event_SignUp_repassword_textfieldFocusGained

    private void SignUp_EmployeeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_EmployeeFocusGained
        // TODO add your handling code here:
        SignUp_error_label.setText("");
    }//GEN-LAST:event_SignUp_EmployeeFocusGained

    private void SignUp_EmployerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SignUp_EmployerFocusGained
        // TODO add your handling code here:
        SignUp_error_label.setText("");
    }//GEN-LAST:event_SignUp_EmployerFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton SignUp_Employee;
    private javax.swing.JRadioButton SignUp_Employer;
    private javax.swing.JTextField SignUp_email_textfield;
    private javax.swing.JLabel SignUp_error_label;
    private javax.swing.JPasswordField SignUp_password_textfield;
    private javax.swing.JPasswordField SignUp_repassword_textfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
